// Header file for the ColorMatch application
// This file is generated by the ColorMatch Application in Learn Mode

// Calibration data
sensorData sdBlack = { 6250, 6100, 7500 };
sensorData sdWhite = { 55420, 58760, 69670 };

// Color Table for matching
typedef struct
{
  char    name[9];  // color name 8+nul
  colorData rgb;    // RGB value
} colorTable;

colorTable ct[] = 
{
  {"WHITE", {254, 249, 253} },
  {"BLACK", {0, 0, 1} },
  {"YELLOW", {225, 192, 73} },
  {"ORANGE", {201, 108, 54} },
  {"RED", {138, 23, 27} },
  {"GREEN", {61, 91, 60} },
  {"BLUE", {46, 74, 114} },
  {"BROWN", {69, 29, 22} },
};
