// Header file for the ColorMatch application
// This file is generated by the ColorMatch Application in Learn Mode

// Calibration data
sensorData sdBlack = { 21050, 17710, 23030 };
sensorData sdWhite = { 187260, 172970, 227420 };

// Color Table for matching
typedef struct
{
  char    name[9];  // color name 8+nul
  colorData rgb;    // RGB value
} colorTable;

colorTable ct[] = 
{
  {"WHITE", {254, 255, 254} },
  {"BLACK", {0, 0, 0} },
  {"YELLOW", {212, 185, 69} },
  {"ORANGE", {206, 115, 59} },
  {"RED", {153, 37, 33} },
  {"GREEN", {81, 109, 61} },
  {"BLUE", {59, 80, 113} },
  {"BROWN", {81, 38, 25} },
};
